; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:rymcu-esp32-devkitc]
platform = espressif32
board = rymcu-esp32-devkitc
framework = arduino
lib_ldf_mode = deep+
lib_deps = 
	mikalhart/TinyGPSPlus@^1.1.0
	adafruit/Adafruit INA219@^1.2.3

board_build.partitions = min_spiffs.csv

; jgn dikomen kalo pake usb
; upload_protocol = esptool

; jgn dikomen kalo pake wifi
upload_protocol = espota
upload_port = 192.168.4.1  ; IP Address ESP32 (Mode AP)
upload_flags =
	--auth=lBU_MEG4   ; <--- Masukkan Password OTA kamu disini
    --port=3232             ; Port default OTA

monitor_speed = 115200